dist: trusty
language: minimal

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
  chrome: stable

cache:
  directories:
    - /home/travis/.volta/
    - /home/travis/.npm/
    - /home/travis/.yarn/

env:
  global:
    - VOLTA_HOME=/home/travis/.volta/
    - PATH=$VOLTA_HOME/bin:$PATH

before_install:
  - curl https://get.volta.sh | bash
  - source /home/travis/.volta/load.sh

install:
  - yarn
  - yarn compile

script:
  - echo "${PATH}"
  - which volta
  - which node
  - which yarn
  - which npm
  - which ember
  - yarn echo:path
  - yarn which:volta
  - yarn which:node
  - yarn which:yarn
  - yarn which:npm
  - yarn which:ember
  - yarn node:debug
  - yarn node:exec "echo \"${PATH}\""
  - yarn node:exec "which volta"
  - yarn node:exec "which node"
  - yarn node:exec "which yarn"
  - yarn node:exec "which npm"
  - yarn node:exec "which ember"
  - yarn node:exec "node ./dist/bin/debug.js"
