dist: trusty
language: minimal

addons:
  apt:
    packages:
      # These are required to run new chrome on old trusty
      - fonts-liberation
      - libappindicator3-1
      - libnss3
      - xdg-utils
      # These are for optimizing screenshots
      - advancecomp
      - optipng
      - perceptualdiff
  chrome: stable

cache:
  directories:
    - /home/travis/.volta/
    - /home/travis/.npm/
    - /home/travis/.yarn/

env:
  global:
    - VOLTA_HOME=/home/travis/.volta/
    - PATH=$VOLTA_HOME/bin:$PATH

before_install:
  - curl https://get.volta.sh | bash
  - source /home/travis/.volta/load.sh
  - git config --global user.name "Tomster"
  - git config --global user.email "tomster@emberjs.com"

install:
  - yarn
  - yarn upgrade ember-cli

script:
  - yarn build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_abcbee76306e_key -iv $encrypted_abcbee76306e_iv -in deploy-keys.tar.gz.enc -out deploy-keys.tar.gz -d

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: ember-learn/super-rentals-tutorial
    branch: master
