dist: trusty
language: minimal

addons:
  apt:
    packages:
      # These are required to run new chrome on old trusty
      - fonts-liberation
      - libappindicator3-1
      - libnss3
      - xdg-utils
  chrome: stable

cache:
  directories:
    - /home/travis/.volta/
    - /home/travis/.npm/
    - /home/travis/.yarn/

env:
  global:
    - VOLTA_HOME=/home/travis/.volta/
    - PATH=$VOLTA_HOME/bin:$PATH

before_install:
  - curl https://get.volta.sh | bash
  - source /home/travis/.volta/load.sh

install:
  - yarn
  - yarn upgrade ember-cli

script:
  - yarn build
